-- data-postgresql.sql
INSERT INTO Question(id, question, parent_id, left_id, right_id, left_answer, right_answer, trip) VALUES
                                                                                                      (1, '쉬러감 or 놀러감', null, 2, 3, '쉬러감', '놀러감', null),
                                                                                                      (2, '힐링 or 도시락', 1, 4, 5, '힐링', '도시락', null),
                                                                                                      (3, '액티비티 or 체험', 1, 6, 7, '액티비티', '체험', null),
                                                                                                      (4, '자연 or 관광', 2, 8, 9, '자연', '관광', null),
                                                                                                      (5, '식사 or 음료', 2, 10, 11, '식사', '음료', null),
                                                                                                      (6, '땅 or 물', 3, 12, 13, '땅', '물', null),
                                                                                                      (7, '역사관람 or 생태체험', 3, 14, 15, '역사관람', '생태체험', null),
                                                                                                      (8, '숲 or 하늘', 4, 16, 17, '숲', '하늘', null),
                                                                                                      (9, '멍때리기 or 노래듣기', 4, 18, 19, '멍때리기', '노래듣기', null),
                                                                                                      (10, '해산물 or 고기', 5, 20, 21, '해산물', '고기', null),
                                                                                                      (11, '무알콜 or 알콜', 5, 22, 23, '무알콜', '알콜', null),
                                                                                                      (12, '발이 땅 or 발이 안닿아', 6, 24, 25, '발이 땅', '발이 안닿아', null),
                                                                                                      (13, '챌린지 or 편안', 6, 26, 27, '챌린지', '편안', null),
                                                                                                      (14, '역사 or 한복', 7, 28, 29, '역사', '한복', null),
                                                                                                      (15, '먹이주기 or 자급자족', 7, 30, 31, '먹이주기', '자급자족', null),
                                                                                                      (16, '공원 or 죽녹원', 8, 32, 33,  '공원', '죽녹원',null),
                                                                                                      (17, '일몰 or 일출', 8, 34, 35,  '일몰', '일출',null),
                                                                                                      (18, '불멍 or 물멍', 9, 36, 37,  '불멍', '물멍',null),
                                                                                                      (19, '밤바다 or 영화', 9, 38, 39,  '밤바다', '영화',null),
                                                                                                      (20, '회 or 조개구이', 10, 40, 41,  '회', '조개구이',null),
                                                                                                      (21, '닭갈비 or 막창', 10, 42, 43,  '닭갈비', '막창',null),
                                                                                                      (22, '커피 or 녹차', 11, 44, 45,  '커피', '녹차',null),
                                                                                                      (23, '막걸리 or 소주', 11, 46, 47,  '막걸리', '소주',null),
                                                                                                      (24, '루지 or 바이킹', 12, 48, 49,  '루지', '바이킹',null),
                                                                                                      (25, '스카이다이빙 or 패러글라이딩', 12, 50, 51,  '스카이다이빙', '패러글라이딩',null),
                                                                                                      (26, '서핑 or 레프팅', 13, 52, 53,  '서핑', '레프팅',null),
                                                                                                      (27, '요트 or 워터슬라이드', 13, 54, 55,  '요트', '워터슬라이드',null),
                                                                                                      (28, '백제 or 신라', 14, 56, 57,  '백제', '신라',null),
                                                                                                      (29, '고궁 or 한옥', 14, 58, 59,  '고궁', '한옥',null),
                                                                                                      (30, '말 or 양', 15, 60, 61,  '말', '양',null),
                                                                                                      (31, '조개 or 빙어', 15, 62, 63,  '조개', '빙어',null),
                                                                                                      (32, '공원', 16, null, null, null, null,'울산'),
                                                                                                      (33, '죽녹원', 16, null, null,  null, null,'담양'),
                                                                                                      (34, '일몰', 17, null, null,  null, null, '해남'),
                                                                                                      (35, '일출', 17, null, null,  null, null, '포항'),
                                                                                                      (36, '불멍', 18, null, null, null, null,'가평'),
                                                                                                      (37, '물멍', 18, null, null, null, null,'목포' ),
                                                                                                      (38, '밤바다', 19, null, null, null, null,'여수'),
                                                                                                      (39, '영화', 19, null, null, null, null,'부산' ),
                                                                                                      (40, '회', 20, null, null, null, null,'속초'),
                                                                                                      (41, '조개구이', 20, null, null, null, null,'보령' ),
                                                                                                      (42, '닭갈비', 21, null, null, null, null,'춘천' ),
                                                                                                      (43, '막창', 21, null, null, null, null,'대구' ),
                                                                                                      (44, '커피', 22, null, null, null, null,'강릉' ),
                                                                                                      (45, '녹차', 22, null, null, null, null,'보성'),
                                                                                                      (46, '막걸리', 23, null, null, null, null,'당진'),
                                                                                                      (47, '소주', 23, null, null, null, null,'안동'),
                                                                                                      (48, '루지', 24, null, null, null, null,'통영'),
                                                                                                      (49, '바이킹', 24, null, null,null, null,'인천'),
                                                                                                      (50, '스카이다이빙', 25, null, null, null, null,'충주'),
                                                                                                      (51, '패러글라이딩', 25, null, null, null, null,'단양'),
                                                                                                      (52, '서핑', 26, null, null, null, null,'양양'),
                                                                                                      (53, '레프팅', 26, null, null, null, null,'인제'),
                                                                                                      (54, '요트', 27, null, null, null, null,'서귀포'),
                                                                                                      (55, '워터슬라이드', 27, null, null, null, null,'천안'),
                                                                                                      (56, '백제', 28, null, null, null, null,'공주'),
                                                                                                      (57, '신라', 28, null, null, null, null,'경주'),
                                                                                                      (58, '고궁', 29, null, null, null, null,'종로구'),
                                                                                                      (59, '한옥', 29, null, null, null, null,'전주'),
                                                                                                      (60, '말', 30, null, null, null, null,'태백'),
                                                                                                      (61, '양', 30, null, null, null, null,'평창'),
                                                                                                      (62, '조개', 31, null, null, null, null,'태안'),
                                                                                                      (63, '빙어', 31, null, null, null, null,'양평');