-- data-postgresql.sql
INSERT INTO Question(id, question, parent_id, left_id, right_id, left_answer, right_answer, trip) VALUES
                                                                                                      (1, '산 or 바다?', null, 2, 3, '산', '바다', null),
                                                                                                      (2, '풍경 or 등산', 1, 4, 5, '풍경', '등산', null),
                                                                                                      (3, '동해 or 서해', 1, 6, 7, '동해', '서해', null),
                                                                                                      (4, '단풍 or 눈', 2, 8, 9, '단풍', '눈', null),
                                                                                                      (5, '흙산 or 돌산', 2, 10, 11, '흙산', '돌산', null),
                                                                                                      (6, '해수욕 or 힐링', 3, 12, 13, '해수욕', '힐링', null),
                                                                                                      (7, '갯벌 or 해수욕장', 3, 14, 15, '갯벌', '해수욕장', null),
                                                                                                      (8, ' or ', 4, 16, 17, '낮', '밤', null),
                                                                                                      (9, ' or ', 4, 18, 19, '아침밥', '저녁밥', null),
                                                                                                      (10, ' or ', 5, 20, 21, '별', '야경', null),
                                                                                                      (11, ' or ', 5, 22, 23, '서핑', '보트', null),
                                                                                                      (12, '서핑 or 튜브', 6, 24, 25, '서핑', '튜브', null),
                                                                                                      (13, '스파 or 먹거리', 6, 26, 27, '스파', '먹거리', null),
                                                                                                      (14, '조개구이 or 조개캐기', 7, 28, 29, '조개구이', '조개캐기', null),
                                                                                                      (15, '거센 파도 or 잔잔한 파도', 7, 30, 31, '거센 파도', '잔잔한 파도', null),
                                                                                                      (16, '산1', 8, null, null,  null, null,''),
                                                                                                      (17, '산2', 8, null, null,  null, null,'' ),
                                                                                                      (18, '산3', 9, null, null, null, null,''),
                                                                                                      (19, '산4', 9, null, null, null, null,'' ),
                                                                                                      (20, '산5', 10, null, null,  null, null,''),
                                                                                                      (21, '산6', 10, null, null,  null, null,'' ),
                                                                                                      (22, '산7', 11, null, null,  null, null,'' ),
                                                                                                      (23, '산8', 11, null, null,  null, null,'' ),
                                                                                                      (24, '서핑', 12, null, null, null, null,'양양' ),
                                                                                                      (25, '튜브', 12, null, null, null, null,'강릉'),
                                                                                                      (26, '스파', 13, null, null, null, null,'태백'),
                                                                                                      (27, '먹거리', 13, null, null, null, null,'속초'),
                                                                                                      (28, '조개구이', 14, 6, 7, null, null,'보령'),
                                                                                                      (29, '조개캐기', 14, null, null,null, null,'태안'),
                                                                                                      (30, '거센 파도', 15, null, null, null, null,'부안'),
                                                                                                      (31, '잔잔한 파도', 15, null, null, null, null,'안면도');